#ifndef PLASIC_STATUS_H
#define PLASIC_STATUS_H

enum plasic_runtime_status
{
    PLASIC_RUNTIME_OK = 0,
    PLASIC_RUNTIME_BAD_ARGUMENT = 1,
    PLASIC_RUNTIME_INITIALIZATION_FAILED = 2,
    PLASIC_RUNTIME_RESTART_FAILED = 3,
    PLASIC_RUNTIME_NUMERICAL_FAILURE = 4,
    PLASIC_RUNTIME_IO_FAILED = 5,
    PLASIC_RUNTIME_UNSUPPORTED_CONFIGURATION = 6
};

#endif
